### ISSUE TITLE
Updaters not running every step of chain, suddenly.

### ISSUE THREAD

**Issue by sanketshahc** [mggg/GerryChain#355]
Hi, the updater functions no longer run every step of the chain, all of the sudden. It was working, and then it suddenly stopped. I even tested mggg's template code, doesn't work there either. Resorting to manual calculation every loop of chain.

**Comment by bsuwal** [comment]
Hi,

Could you post a snippet of the code you used, what you were expecting and what the outputs you got instead were?

**Comment by frnsys** [comment]
I noticed this too, with a very simple updater:

```
def test_updater(partition):
    print('im called')
    return 'foo'

initial_partition = Partition(
    # ...
    updaters={'test_updater': test_updater}
    # ...
)
```

"im called" isn't printed every iteration of the chain; it looks like it's only called if I access the updater, e.g. `partition['test_updater']`. I'm guessing this is the expected behavior?

**Comment by apizzimenti** [comment]
Expected behavior is that individual updater functions *are not* called at each chain step unless they are explicitly called by the user, but only because of a quirk in the `Partition` class. Updaters are held in a cache internal to each `Partition` instance: this cache is intended to store the values of the updaters at each iteration of the chain, but because new `Partition` instances overwrites the cache *even if its parent has a populated cache object*, all updater keys are "new" to the cache object and have to be re-computed each time a new `Partition` is instantiated.

For reference, see the `Partition` class – specifically the constructor and the `_from_parent()` method – and the `recom()` proposal function.
