### ISSUE TITLE
Saving and loading Partition object

### ISSUE THREAD

**Issue by itsSauravK** [mggg/GerryChain#409]
I have been going through the documentation and previous issues. I was looking for a way to save Partition objects generated from the Markov chain once, save it as a Json file and then load the same Json as a Partition object in other code so I can recompute everything using the same data

Would really appreciate any help on this.

**Comment by cdonnay** [comment]
My work around for this is to use the pickle module, and to only try to save the assignment dictionary from each Partition object, rather than the entire Partition object. Then, to use it later, I load in the pickle file with the assignments, and create Partitions using the assignments.

**Comment by peterrrock2** [comment]
Ah, there is a bit of nuance that is worth mentioning here.

So, in general, using the pickle module is a good approach for saving intermediate `Partition` objects, but this will not work in general as is evidenced in #325. In fact, making these work in general is undesirable behavior since we sometimes need/want to write updaters in terms of lambda functions which are inherently unpickle-able. However, if you are looking to just replay your chain so that you can either use [PCompress](https://github.com/mggg/pcompress), or if you would like to save intermediate stats, you may reference the "Good Data Practices" section of the documentation coming out in version 0.3.0 here in the next couple of days. If you need any other assistance, please let us know!

**Comment by itsSauravK** [comment]
Thank you!
